# Generated by Django 6.0.3 on 2026-03-14 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Marca de tiempo automática al momento de la inserción.', verbose_name='Fecha de creación')),
                ('calle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Calle')),
                ('no_exterior', models.CharField(blank=True, max_length=50, null=True, verbose_name='Núm. Exterior')),
                ('no_interior', models.CharField(blank=True, max_length=50, null=True, verbose_name='Núm. Interior')),
                ('colonia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Colonia')),
                ('codigo_postal', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código Postal')),
                ('municipio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Municipio')),
                ('estado', models.CharField(help_text='Estado o entidad federativa. Campo obligatorio.', max_length=100, verbose_name='Estado')),
                ('referencia_adicional', models.TextField(blank=True, help_text='Indicaciones extra para localización del domicilio.', null=True, verbose_name='Referencia Adicional')),
                ('creado_por', models.ForeignKey(blank=True, help_text='Usuario del sistema que registró este objeto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Domicilio',
                'verbose_name_plural': 'Domicilios',
                'db_table': 'domicilios',
                'ordering': ['estado', 'municipio'],
            },
        ),
    ]
