# Generated by Django 6.0.3 on 2026-03-14 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AddField(
            model_name='user',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, help_text='Se actualiza automáticamente cada vez que se modifica el registro del usuario.', verbose_name='Última Actualización del Perfil'),
        ),
        migrations.AddField(
            model_name='user',
            name='rfc',
            field=models.CharField(blank=True, help_text='Registro Federal de Contribuyentes del operador. Opcional pero único si se captura.', max_length=13, null=True, unique=True, verbose_name='RFC'),
        ),
        migrations.AddField(
            model_name='user',
            name='rol_sistema',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('GESTOR', 'Gestor de Contratos'), ('REVISOR', 'Revisor / Auditor'), ('CONSULTOR', 'Consultor (Solo Lectura)')], default='CONSULTOR', help_text='Define el nivel de acceso global del usuario en Adcon. El permiso granular se gestiona mediante Groups de Django.', max_length=20, verbose_name='Rol en el Sistema'),
        ),
        migrations.AddField(
            model_name='user',
            name='telefono',
            field=models.CharField(blank=True, help_text='Número de contacto para soporte y notificaciones urgentes.', max_length=30, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='usuarios',
        ),
    ]
