# Generated by Django 6.0.3 on 2026-03-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_user_fecha_actualizacion_user_rfc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rol_sistema',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('MANAGER', 'Gestor de Contratos'), ('EDITOR', 'Editor'), ('READER', 'Lector (Solo Lectura)')], db_index=True, default='READER', help_text='Define el nivel de acceso del usuario en la plataforma Adcon. ADMIN: acceso total. MANAGER: CRUD en negocio. EDITOR: consulta y edición. READER: solo lectura.', max_length=20, verbose_name='Rol en el Sistema'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización del Perfil'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rfc',
            field=models.CharField(blank=True, help_text='Registro Federal de Contribuyentes del operador. Único si se captura.', max_length=13, null=True, unique=True, verbose_name='RFC'),
        ),
    ]
