# Generated by Django 6.0.3 on 2026-03-18 16:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parte',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Marca de tiempo automática al momento de la inserción.', verbose_name='Fecha de creación')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID Único')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(blank=True, max_length=30, null=True, verbose_name='Teléfono')),
                ('creado_por', models.ForeignKey(blank=True, help_text='Usuario del sistema que registró este objeto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('domicilio', models.ForeignKey(blank=True, help_text='Domicilio principal de la parte.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partes', to='addresses.domicilio', verbose_name='Domicilio Fiscal')),
                ('tipo_parte', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='partes', to='core.tipoparte', verbose_name='Tipo de Parte')),
            ],
            options={
                'verbose_name': 'Parte',
                'verbose_name_plural': 'Partes',
                'db_table': 'partes',
                'ordering': ['tipo_parte', 'email'],
            },
        ),
        migrations.CreateModel(
            name='PersonaFisica',
            fields=[
                ('parte', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='persona_fisica', serialize=False, to='parties.parte', verbose_name='Parte Base')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre(s)')),
                ('apellido_paterno', models.CharField(max_length=100, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido Materno')),
                ('rfc', models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='RFC')),
                ('curp', models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='CURP')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('nacionalidad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nacionalidad')),
            ],
            options={
                'verbose_name': 'Persona Física',
                'verbose_name_plural': 'Personas Físicas',
                'db_table': 'personas_fisicas',
                'ordering': ['apellido_paterno', 'apellido_materno', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID Único')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Sucursal')),
                ('telefono', models.CharField(blank=True, max_length=30, null=True, verbose_name='Teléfono Sucursal')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Correo Sucursal')),
                ('domicilio', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sucursales', to='addresses.domicilio', verbose_name='Dirección de la Sucursal')),
                ('parte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursales', to='parties.parte', verbose_name='Entidad Principal')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'db_table': 'sucursales',
                'ordering': ['parte', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PersonaMoral',
            fields=[
                ('parte', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='persona_moral', serialize=False, to='parties.parte', verbose_name='Parte Base')),
                ('razon_social', models.CharField(max_length=255, verbose_name='Razón Social')),
                ('rfc', models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='RFC')),
                ('fecha_constitucion', models.DateField(verbose_name='Fecha de Constitución')),
                ('objeto_social', models.TextField(blank=True, null=True, verbose_name='Objeto Social')),
                ('apoderado_general', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poderes_generales', to='parties.parte', verbose_name='Apoderado General')),
                ('organo_administracion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas', to='core.organoadministracion', verbose_name='Órgano de Administración')),
                ('representante_legal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='representaciones_legales', to='parties.parte', verbose_name='Representante Legal')),
            ],
            options={
                'verbose_name': 'Persona Moral',
                'verbose_name_plural': 'Personas Morales',
                'db_table': 'personas_morales',
                'ordering': ['razon_social'],
            },
        ),
    ]
