# Generated by Django 6.0.3 on 2026-03-14 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Marca de tiempo automática al momento de la inserción.', verbose_name='Fecha de creación')),
                ('nombre', models.CharField(help_text='Nombre completo de la persona física o denominación social de la persona moral.', max_length=255, verbose_name='Nombre o Razón Social')),
                ('creado_por', models.ForeignKey(blank=True, help_text='Usuario del sistema que registró este objeto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('tipo_parte', models.ForeignKey(blank=True, help_text='Clasificación jurídica de la parte: Persona Física, Moral, Fideicomiso.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='partes', to='core.tipoparte', verbose_name='Tipo de Parte')),
            ],
            options={
                'verbose_name': 'Parte',
                'verbose_name_plural': 'Partes',
                'db_table': 'partes',
                'ordering': ['nombre'],
            },
        ),
    ]
