# Generated by Django 6.0.3 on 2026-03-14 09:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
        ('core', '0001_initial'),
        ('parties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaFisica',
            fields=[
                ('parte', models.OneToOneField(help_text='Registro base en la tabla partes al que pertenece este perfil.', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='personafisica', serialize=False, to='parties.parte', verbose_name='Parte Base')),
                ('nombre', models.CharField(help_text='Nombre o nombres de pila de la persona física.', max_length=100, verbose_name='Nombre(s)')),
                ('apellido_paterno', models.CharField(max_length=100, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido Materno')),
                ('rfc', models.CharField(blank=True, help_text='Registro Federal de Contribuyentes (13 caracteres para persona física).', max_length=13, null=True, unique=True, verbose_name='RFC')),
                ('curp', models.CharField(blank=True, help_text='Clave Única de Registro de Población (18 caracteres).', max_length=18, null=True, unique=True, verbose_name='CURP')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('nacionalidad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nacionalidad')),
            ],
            options={
                'verbose_name': 'Persona Física',
                'verbose_name_plural': 'Personas Físicas',
                'db_table': 'personas_fisicas',
            },
        ),
        migrations.AlterModelOptions(
            name='parte',
            options={'ordering': ['id'], 'verbose_name': 'Parte', 'verbose_name_plural': 'Partes'},
        ),
        migrations.RemoveField(
            model_name='parte',
            name='nombre',
        ),
        migrations.AddField(
            model_name='parte',
            name='domicilio',
            field=models.ForeignKey(blank=True, help_text='Dirección principal o fiscal registrada en el sistema.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partes', to='addresses.domicilio', verbose_name='Domicilio Fiscal / Principal'),
        ),
        migrations.AddField(
            model_name='parte',
            name='email',
            field=models.EmailField(blank=True, help_text='Dirección de correo para notificaciones y comunicaciones formales.', max_length=254, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AddField(
            model_name='parte',
            name='telefono',
            field=models.CharField(blank=True, help_text='Número de contacto principal.', max_length=30, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='parte',
            name='tipo_parte',
            field=models.ForeignKey(default=None, help_text='Clasificación jurídica: Persona Física, Moral, Fideicomiso, etc.', on_delete=django.db.models.deletion.RESTRICT, related_name='partes', to='core.tipoparte', verbose_name='Tipo de Parte'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PersonaMoral',
            fields=[
                ('parte', models.OneToOneField(help_text='Registro base en la tabla partes al que pertenece este perfil corporativo.', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='personamoral', serialize=False, to='parties.parte', verbose_name='Parte Base')),
                ('razon_social', models.CharField(help_text='Denominación o razón social completa tal como aparece en el acta constitutiva.', max_length=255, verbose_name='Razón Social')),
                ('rfc', models.CharField(blank=True, help_text='Registro Federal de Contribuyentes (12 caracteres para persona moral).', max_length=12, null=True, unique=True, verbose_name='RFC')),
                ('fecha_constitucion', models.DateField(help_text='Fecha en que se protocolizó el acta constitutiva ante notario.', verbose_name='Fecha de Constitución')),
                ('objeto_social', models.TextField(blank=True, help_text='Descripción de las actividades y propósitos autorizados para la sociedad.', null=True, verbose_name='Objeto Social')),
                ('apoderado_general', models.ForeignKey(blank=True, help_text='Apoderado con facultades generales distintas al representante legal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apoderado_general_de', to='parties.parte', verbose_name='Apoderado General')),
                ('organo_administracion', models.ForeignKey(blank=True, help_text='Tipo de órgano directivo: Administrador Único, Consejo de Administración, etc.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personas_morales', to='core.organoadministracion', verbose_name='Órgano de Administración')),
                ('representante_legal', models.ForeignKey(blank=True, help_text='Persona física que firma por default en nombre de la empresa.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='representante_legal_de', to='parties.parte', verbose_name='Representante Legal')),
            ],
            options={
                'verbose_name': 'Persona Moral',
                'verbose_name_plural': 'Personas Morales',
                'db_table': 'personas_morales',
            },
        ),
        migrations.CreateModel(
            name='AccionistaSocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Marca de tiempo automática al momento de la inserción.', verbose_name='Fecha de creación')),
                ('porcentaje_participacion', models.DecimalField(decimal_places=2, help_text='Porcentaje del capital social que posee el accionista. Rango: 0.01 – 100.', max_digits=5, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje de Participación (%)')),
                ('fecha_adquisicion', models.DateField(blank=True, help_text='Fecha en que se adquirió esta participación accionaria.', null=True, verbose_name='Fecha de Adquisición')),
                ('tipo_participacion', models.CharField(blank=True, help_text='Serie o clase de acciones. Ej: Serie A, Capital Variable.', max_length=100, null=True, verbose_name='Tipo de Participación')),
                ('accionista', models.ForeignKey(help_text='Parte que posee acciones o participación en la sociedad.', on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='parties.parte', verbose_name='Accionista')),
                ('creado_por', models.ForeignKey(blank=True, help_text='Usuario del sistema que registró este objeto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('sociedad', models.ForeignKey(help_text='Persona moral cuyo capital se está distribuyendo.', on_delete=django.db.models.deletion.CASCADE, related_name='accionistas', to='parties.parte', verbose_name='Sociedad')),
            ],
            options={
                'verbose_name': 'Accionista / Socio',
                'verbose_name_plural': 'Accionistas / Socios',
                'db_table': 'accionistas_socios',
                'ordering': ['-porcentaje_participacion'],
                'unique_together': {('sociedad', 'accionista')},
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Marca de tiempo automática al momento de la inserción.', verbose_name='Fecha de creación')),
                ('nombre', models.CharField(help_text='Nombre o identificador interno de la sucursal. Único por parte.', max_length=100, verbose_name='Nombre de Sucursal')),
                ('telefono', models.CharField(blank=True, max_length=30, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('creado_por', models.ForeignKey(blank=True, help_text='Usuario del sistema que registró este objeto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('domicilio', models.ForeignKey(help_text='Dirección física de la sucursal.', on_delete=django.db.models.deletion.RESTRICT, related_name='sucursales', to='addresses.domicilio', verbose_name='Domicilio')),
                ('parte', models.ForeignKey(help_text='Entidad propietaria o responsable de esta sucursal.', on_delete=django.db.models.deletion.CASCADE, related_name='sucursales', to='parties.parte', verbose_name='Parte')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'db_table': 'sucursales',
                'ordering': ['parte', 'nombre'],
                'unique_together': {('parte', 'nombre')},
            },
        ),
    ]
