# Generated by Django 6.0.3 on 2026-03-18 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('instruments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Marca de tiempo automática al momento de la inserción.', verbose_name='Fecha de creación')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre(s)')),
                ('apellido_paterno', models.CharField(max_length=100, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido Materno')),
                ('numero_notaria', models.IntegerField(verbose_name='Número de Notaría')),
                ('distrito', models.CharField(help_text='Ej: Ciudad de México, Estado de Morelos.', max_length=100, verbose_name='Distrito / Entidad')),
                ('rfc', models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='RFC')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
            ],
            options={
                'verbose_name': 'Notario / Fedatario',
                'verbose_name_plural': 'Notarios / Fedatarios',
                'db_table': 'notarios',
                'ordering': ['distrito', 'numero_notaria'],
            },
        ),
        migrations.CreateModel(
            name='Escritura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Marca de tiempo automática al momento de la inserción.', verbose_name='Fecha de creación')),
                ('titulo', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Título')),
                ('numero_escritura', models.CharField(max_length=50, verbose_name='Número de Escritura')),
                ('numero_testimonio', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Testimonio')),
                ('datos_registro_publico', models.CharField(blank=True, help_text='Ej: "Libro 1, Foja 10" o "RPC 2025/12345".', max_length=100, null=True, verbose_name='Datos Registro Público')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('nombre_archivo', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Nombre de Archivo')),
                ('ruta_archivo', models.FileField(blank=True, help_text='PDF de la escritura. Almacenado cifrado en AWS S3 con AES256.', null=True, upload_to='legal/escrituras/', verbose_name='Escritura Digital (S3)')),
                ('fecha_otorgamiento', models.DateField(verbose_name='Fecha de Otorgamiento')),
                ('creado_por', models.ForeignKey(blank=True, help_text='Usuario del sistema que registró este objeto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escrituras', to='instruments.instrumento', verbose_name='Instrumento')),
                ('tipo_escritura', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='escrituras', to='core.tipoescritura', verbose_name='Tipo de Escritura')),
            ],
            options={
                'verbose_name': 'Escritura',
                'verbose_name_plural': 'Escrituras',
                'db_table': 'escrituras',
                'ordering': ['-fecha_otorgamiento'],
            },
        ),
        migrations.CreateModel(
            name='EscrituraFacultad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limitacion_descripcion', models.TextField(blank=True, help_text='Descripción de la restricción a la facultad otorgada. Ej: "Solo hasta $500,000".', null=True, verbose_name='Limitación')),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='escrituras', to='core.catfacultad', verbose_name='Facultad')),
            ],
            options={
                'verbose_name': 'Escritura Facultad',
                'verbose_name_plural': 'Escrituras Facultades',
                'db_table': 'escrituras_facultades',
            },
        ),
        migrations.CreateModel(
            name='EscrituraPersonalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Marca de tiempo automática al momento de la inserción.', verbose_name='Fecha de creación')),
                ('numero_escritura', models.CharField(max_length=100, verbose_name='Número de Escritura')),
                ('fecha_otorgamiento', models.DateField(verbose_name='Fecha de Otorgamiento')),
                ('lugar_otorgamiento', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lugar de Otorgamiento')),
                ('comentarios', models.TextField(blank=True, help_text='Ej: "Poder limitado a $500,000 MXN".', null=True, verbose_name='Comentarios / Limitaciones')),
                ('nombre_archivo', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Nombre de Archivo')),
                ('ruta_archivo', models.FileField(blank=True, null=True, upload_to='legal/poderes/', verbose_name='PDF del Poder (S3)')),
                ('creado_por', models.ForeignKey(blank=True, help_text='Usuario del sistema que registró este objeto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('instrumento_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escrituras_personalidad', to='instruments.instrumento', verbose_name='Instrumento de Origen')),
            ],
            options={
                'verbose_name': 'Escritura de Personalidad / Poder',
                'verbose_name_plural': 'Escrituras de Personalidad / Poderes',
                'db_table': 'escrituras_personalidad',
            },
        ),
    ]
