# Generated by Django 6.0.3 on 2026-03-18 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('legal', '0001_initial'),
        ('parties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='escriturapersonalidad',
            name='representado',
            field=models.ForeignKey(help_text='Persona moral en cuyo nombre actúa el representante.', on_delete=django.db.models.deletion.RESTRICT, related_name='poderes_como_representado', to='parties.parte', verbose_name='Representado (Empresa)'),
        ),
        migrations.AddField(
            model_name='escriturapersonalidad',
            name='representante',
            field=models.ForeignKey(help_text='Persona física que actúa en nombre de la persona moral.', on_delete=django.db.models.deletion.RESTRICT, related_name='poderes_como_representante', to='parties.parte', verbose_name='Representante (Delegado)'),
        ),
        migrations.AddField(
            model_name='escriturafacultad',
            name='escritura_personalidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facultades', to='legal.escriturapersonalidad', verbose_name='Escritura de Personalidad'),
        ),
        migrations.AddField(
            model_name='notario',
            name='creado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario del sistema que registró este objeto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='notario',
            name='tipo_notario',
            field=models.ForeignKey(help_text='Ej: Notario Público, Corredor Público.', on_delete=django.db.models.deletion.RESTRICT, related_name='notarios', to='core.tiponotario', verbose_name='Tipo de Fedatario'),
        ),
        migrations.AddField(
            model_name='escriturapersonalidad',
            name='notario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escrituras_personalidad', to='legal.notario', verbose_name='Notario'),
        ),
        migrations.AddField(
            model_name='escritura',
            name='notario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='escrituras', to='legal.notario', verbose_name='Notario'),
        ),
        migrations.AlterUniqueTogether(
            name='escriturafacultad',
            unique_together={('escritura_personalidad', 'facultad')},
        ),
        migrations.AlterUniqueTogether(
            name='notario',
            unique_together={('distrito', 'numero_notaria')},
        ),
        migrations.AlterUniqueTogether(
            name='escriturapersonalidad',
            unique_together={('representante', 'representado', 'numero_escritura')},
        ),
    ]
