# Generated by Django 6.0.3 on 2026-03-18 16:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Marca de tiempo automática al momento de la inserción.', verbose_name='Fecha de creación')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID Único')),
                ('clave_catastral', models.CharField(help_text='Identificador oficial ante el catastro.', max_length=100, unique=True, verbose_name='Clave Catastral')),
                ('descripcion', models.TextField(blank=True, help_text='Detalles adicionales del inmueble.', null=True, verbose_name='Descripción')),
                ('superficie_terreno_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Superficie Terreno (m2)')),
                ('superficie_construccion_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Superficie Construcción (m2)')),
                ('creado_por', models.ForeignKey(blank=True, help_text='Usuario del sistema que registró este objeto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('domicilio', models.ForeignKey(help_text='Dirección física del inmueble.', on_delete=django.db.models.deletion.RESTRICT, related_name='inmuebles', to='addresses.domicilio', verbose_name='Ubicación')),
            ],
            options={
                'verbose_name': 'Inmueble',
                'verbose_name_plural': 'Inmuebles',
                'db_table': 'inmuebles',
                'ordering': ['clave_catastral'],
            },
        ),
    ]
