# Generated by Django 6.0.3 on 2026-03-14 08:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0001_initial'),
        ('core', '0001_initial'),
        ('parties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Marca de tiempo automática al momento de la inserción.', verbose_name='Fecha de creación')),
                ('clave_catastral', models.CharField(help_text='Identificador único ante el registro público de la propiedad.', max_length=100, unique=True, verbose_name='Clave Catastral')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción libre del inmueble: materiales, estado, instalaciones especiales.', null=True, verbose_name='Descripción')),
                ('superficie_terreno_m2', models.DecimalField(blank=True, decimal_places=2, help_text='Área total del terreno en metros cuadrados. Debe ser >= 0.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Superficie de Terreno (m²)')),
                ('superficie_construccion_m2', models.DecimalField(blank=True, decimal_places=2, help_text='Área construida del inmueble en metros cuadrados. Debe ser >= 0.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Superficie de Construcción (m²)')),
                ('creado_por', models.ForeignKey(blank=True, help_text='Usuario del sistema que registró este objeto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('domicilio', models.ForeignKey(help_text='Ubicación física del inmueble según el registro catastral.', on_delete=django.db.models.deletion.RESTRICT, related_name='inmuebles', to='addresses.domicilio', verbose_name='Domicilio')),
                ('propietario', models.ForeignKey(blank=True, help_text='Parte que ostenta la titularidad del inmueble al momento del registro.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inmuebles_propietario', to='parties.parte', verbose_name='Propietario')),
                ('tipo_inmueble', models.ForeignKey(help_text='Clasificación del activo: Casa, Local, Terreno, Bodega, etc.', on_delete=django.db.models.deletion.RESTRICT, related_name='inmuebles', to='core.tipoinmueble', verbose_name='Tipo de Inmueble')),
            ],
            options={
                'verbose_name': 'Inmueble',
                'verbose_name_plural': 'Inmuebles',
                'db_table': 'inmuebles',
                'ordering': ['clave_catastral'],
            },
        ),
    ]
