# Generated by Django 6.0.3 on 2026-03-18 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('core', '0001_initial'),
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='propietario',
            field=models.ForeignKey(blank=True, help_text='Dueño actual del inmueble.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propiedades', to='parties.parte', verbose_name='Propietario'),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='tipo_inmueble',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='inmuebles', to='core.tipoinmueble', verbose_name='Tipo de Inmueble'),
        ),
    ]
