# Generated by Django 6.0.3 on 2026-03-18 16:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccionistaEnActo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_acciones', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total de Acciones')),
                ('acciones_capital_fijo', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Acciones Capital Fijo')),
                ('acciones_capital_variable', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Acciones Capital Variable')),
                ('acciones_otro_tipo', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Acciones Otro Tipo')),
                ('rfc_socio_momentaneo', models.CharField(blank=True, help_text='Captura histórica del RFC tal como estaba al momento del acto.', max_length=13, null=True, verbose_name='RFC del Socio (histórico)')),
            ],
            options={
                'verbose_name': 'Accionista en Acto',
                'verbose_name_plural': 'Accionistas en Acto',
                'db_table': 'accionistas_en_acto',
            },
        ),
        migrations.CreateModel(
            name='ActoCorporativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Marca de tiempo automática al momento de la inserción.', verbose_name='Fecha de creación')),
                ('libro_asambleas_foja', models.CharField(blank=True, max_length=100, null=True, verbose_name='Foja Libro de Asambleas')),
                ('libro_var_capital_foja', models.CharField(blank=True, max_length=100, null=True, verbose_name='Foja Libro de Variaciones de Capital')),
                ('libro_reg_acc_foja', models.CharField(blank=True, max_length=100, null=True, verbose_name='Foja Libro Registro de Acciones')),
                ('fecha_acto', models.DateField(verbose_name='Fecha del Acto')),
                ('contenido', models.TextField(help_text='Resumen o texto de los acuerdos tomados en el acto.', verbose_name='Contenido')),
                ('capital_social_fijo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Capital Social Fijo')),
                ('capital_social_variable', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Capital Social Variable')),
                ('clausula_extranjeros', models.BooleanField(default=False, help_text='Indica si se adoptó la cláusula de admisión de extranjeros (Cláusula Calvo).', verbose_name='¿Cláusula de Extranjeros?')),
                ('restricciones_venta_acciones', models.TextField(blank=True, null=True, verbose_name='Restricciones de Venta de Acciones')),
            ],
            options={
                'verbose_name': 'Acto Corporativo',
                'verbose_name_plural': 'Actos Corporativos',
                'db_table': 'actos_corporativos',
                'ordering': ['-fecha_acto'],
            },
        ),
        migrations.CreateModel(
            name='ArchivoFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Marca de tiempo automática al momento de la inserción.', verbose_name='Fecha de creación')),
                ('nombre', models.CharField(help_text='Ej: "Carpeta Arrendamiento 2025" o "Foja 10 del Libro de Actas".', max_length=255, verbose_name='Nombre del Paquete Físico')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('cantidad', models.IntegerField(blank=True, help_text='Número de fojas, carpetas u hojas contenidas en el paquete.', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('ubicacion', models.CharField(blank=True, help_text='Referencia de localización en el archivo. Ej: "Pasillo B, Estante 4".', max_length=255, null=True, verbose_name='Ubicación Física')),
                ('caja', models.CharField(blank=True, help_text='Identificador de la caja de archivo. Ej: "Caja-2025-001".', max_length=50, null=True, verbose_name='Caja')),
                ('fecha_ingreso', models.DateField(blank=True, null=True, verbose_name='Fecha de Ingreso al Archivo')),
            ],
            options={
                'verbose_name': 'Archivo Físico',
                'verbose_name_plural': 'Archivos Físicos',
                'db_table': 'archivos_fisicos',
                'ordering': ['instrumento', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Marca de tiempo automática al momento de la inserción.', verbose_name='Fecha de creación')),
                ('num_instrumento', models.CharField(help_text='Clave única que identifica al instrumento en el CLM. Ej: CONT-2025-001.', max_length=50, unique=True, verbose_name='Número de Instrumento')),
                ('titulo', models.CharField(help_text='Nombre oficial completo del instrumento jurídico.', max_length=1024, verbose_name='Título')),
                ('dato_maestro_cliente', models.CharField(blank=True, db_index=True, help_text='Identificador en sistemas externos del cliente (SAP, ERP) para conciliación.', max_length=100, null=True, verbose_name='Dato Maestro (Cliente)')),
                ('es_renovacion_automatica', models.BooleanField(default=False, help_text='Si True, el sistema generará alertas de vencimiento para tramitar la renovación.', verbose_name='¿Renovación Automática?')),
                ('fecha_inicio', models.DateField(help_text='Fecha a partir de la cual el instrumento produce efectos jurídicos.', verbose_name='Fecha de Inicio')),
                ('fecha_termino', models.DateField(blank=True, help_text='Fecha de vencimiento pactada. NULL indica vigencia indefinida.', null=True, verbose_name='Fecha de Término')),
                ('fecha_firma', models.DateField(blank=True, null=True, verbose_name='Fecha de Firma')),
                ('rfc_facturacion', models.CharField(blank=True, help_text='RFC al que se deben emitir las facturas electrónicas de este contrato.', max_length=13, null=True, verbose_name='RFC de Facturación')),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='Comentarios')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Instrumento',
                'verbose_name_plural': 'Instrumentos',
                'db_table': 'instrumentos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Concurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Marca de tiempo automática al momento de la inserción.', verbose_name='Fecha de creación')),
                ('numero_concurso', models.CharField(help_text='Clave oficial del proceso de contratación, único en el sistema.', max_length=100, unique=True, verbose_name='Número de Concurso')),
                ('titulo', models.CharField(help_text='Nombre descriptivo del concurso tal como aparece en las bases.', max_length=1024, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha_publicacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Publicación')),
                ('fecha_presentacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Presentación')),
                ('fecha_fallo', models.DateField(verbose_name='Fecha de Fallo / Adjudicación')),
                ('presupuesto_base', models.DecimalField(blank=True, decimal_places=2, help_text='Monto máximo presupuestal publicado en las bases del concurso.', max_digits=15, null=True, verbose_name='Presupuesto Base')),
                ('fundamento_legal', models.CharField(blank=True, help_text='Artículo o ley que respalda la elección del tipo de concurso.', max_length=255, null=True, verbose_name='Fundamento Legal')),
            ],
            options={
                'verbose_name': 'Concurso',
                'verbose_name_plural': 'Concursos',
                'db_table': 'concursos',
                'ordering': ['-fecha_fallo'],
            },
        ),
        migrations.CreateModel(
            name='InstrumentoParte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Marca de tiempo automática al momento de la inserción.', verbose_name='Fecha de creación')),
                ('es_principal_para_rol', models.BooleanField(default=False, help_text='Indica si esta parte es la principal dentro de este rol (ej: Arrendatario Principal).', verbose_name='¿Principal para el Rol?')),
                ('fecha_asociacion', models.DateField(help_text='Fecha en que esta parte se vinculó formalmente al instrumento.', verbose_name='Fecha de Asociación')),
            ],
            options={
                'verbose_name': 'Instrumento-Parte',
                'verbose_name_plural': 'Instrumentos-Partes',
                'db_table': 'instrumento_parte',
            },
        ),
    ]
