# Generated by Django 6.0.3 on 2026-03-18 16:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0001_initial'),
        ('assets', '0002_initial'),
        ('core', '0001_initial'),
        ('instruments', '0001_initial'),
        ('parties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accionistaenacto',
            name='socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='actos_como_socio', to='parties.parte', verbose_name='Socio'),
        ),
        migrations.AddField(
            model_name='actocorporativo',
            name='creado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario del sistema que registró este objeto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='actocorporativo',
            name='domicilio_social',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='actos_corporativos', to='addresses.domicilio', verbose_name='Domicilio Social'),
        ),
        migrations.AddField(
            model_name='actocorporativo',
            name='organo_administracion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actos', to='core.organoadministracion', verbose_name='Órgano de Administración'),
        ),
        migrations.AddField(
            model_name='actocorporativo',
            name='tipo_convocatoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actos', to='core.tipoconvocatoria', verbose_name='Tipo de Convocatoria'),
        ),
        migrations.AddField(
            model_name='accionistaenacto',
            name='acto_corporativo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accionistas', to='instruments.actocorporativo', verbose_name='Acto Corporativo'),
        ),
        migrations.AddField(
            model_name='archivofisico',
            name='creado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario del sistema que registró este objeto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='creado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario del sistema que registró este objeto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='estatus_instrumento',
            field=models.ForeignKey(help_text='Estado actual del ciclo de vida: Borrador, Vigente, Vencido, Cancelado.', on_delete=django.db.models.deletion.RESTRICT, related_name='instrumentos', to='core.estatusinstrumento', verbose_name='Estatus'),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='instrumento_vinculado',
            field=models.ForeignKey(blank=True, help_text='Contrato principal al que este instrumento está subordinado (ej: un Anexo del principal).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instrumentos_dependientes', to='instruments.instrumento', verbose_name='Instrumento Vinculado'),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='prioridad_instrumento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='instrumentos', to='core.prioridadinstrumento', verbose_name='Prioridad'),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='tipo_contraprestacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instrumentos', to='core.tipocontraprestacion', verbose_name='Tipo de Contraprestación'),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='tipo_firma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instrumentos', to='core.tipofirma', verbose_name='Tipo de Firma'),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='tipo_instrumento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='instrumentos', to='core.tipoinstrumento', verbose_name='Tipo de Instrumento'),
        ),
        migrations.AddField(
            model_name='archivofisico',
            name='instrumento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_fisicos', to='instruments.instrumento', verbose_name='Instrumento'),
        ),
        migrations.AddField(
            model_name='actocorporativo',
            name='instrumento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actos_corporativos', to='instruments.instrumento', verbose_name='Instrumento'),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='concurso',
            field=models.ForeignKey(blank=True, help_text='Proceso de adjudicación que originó este contrato. Puede ser nulo en contratos privados.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instrumentos', to='instruments.concurso', verbose_name='Concurso de Origen'),
        ),
        migrations.AddField(
            model_name='concurso',
            name='creado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario del sistema que registró este objeto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='concurso',
            name='tipo_concurso',
            field=models.ForeignKey(help_text='Modalidad de adjudicación: Licitación Pública, Invitación a 3, Adjudicación Directa.', on_delete=django.db.models.deletion.RESTRICT, related_name='concursos', to='core.tipoconcurso', verbose_name='Tipo de Concurso'),
        ),
        migrations.AddField(
            model_name='instrumentoparte',
            name='creado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario del sistema que registró este objeto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='instrumentoparte',
            name='domicilio_notificaciones',
            field=models.ForeignKey(blank=True, help_text='Domicilio convencional pactado en este contrato para recibir notificaciones.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vinculos_instrumento', to='addresses.domicilio', verbose_name='Domicilio para Notificaciones'),
        ),
        migrations.AddField(
            model_name='instrumentoparte',
            name='instrumento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partes_vinculadas', to='instruments.instrumento', verbose_name='Instrumento'),
        ),
        migrations.AddField(
            model_name='instrumentoparte',
            name='parte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrumentos_vinculados', to='parties.parte', verbose_name='Parte'),
        ),
        migrations.AddField(
            model_name='instrumentoparte',
            name='rol',
            field=models.ForeignKey(help_text='Papel jurídico de la parte en este contrato: Arrendador, Contratista, Garante, etc.', on_delete=django.db.models.deletion.RESTRICT, related_name='vinculos', to='core.rol', verbose_name='Rol en el Instrumento'),
        ),
        migrations.CreateModel(
            name='Arrendamiento',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Marca de tiempo automática al momento de la inserción.', verbose_name='Fecha de creación')),
                ('instrumento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='arrendamiento', serialize=False, to='instruments.instrumento', verbose_name='Instrumento Base')),
                ('meses_arrendamiento', models.IntegerField(help_text='Plazo total del arrendamiento expresado en meses.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Duración (meses)')),
                ('fecha_pago_renta', models.DateField(help_text='Día del mes en que debe cubrirse la renta. Ej: 5 de cada mes.', verbose_name='Fecha de Pago de Renta')),
                ('monto_renta_sin_iva', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Monto de Renta (sin IVA)')),
                ('monto_deposito', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Depósito en Garantía')),
                ('actualizacion_renta_inpc', models.BooleanField(default=False, help_text='Si True, la renta se actualiza anualmente con base en el Índice Nacional de Precios al Consumidor.', verbose_name='¿Actualización por INPC?')),
                ('poliza_responsabilidad_civil', models.BooleanField(default=False, help_text='Si True, el arrendatario debe contratar y mantener vigente una póliza de responsabilidad civil.', verbose_name='¿Requiere Póliza RC?')),
                ('creado_por', models.ForeignKey(blank=True, help_text='Usuario del sistema que registró este objeto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('inmueble', models.ForeignKey(help_text='Bien inmueble que es objeto del contrato de arrendamiento.', on_delete=django.db.models.deletion.RESTRICT, related_name='arrendamientos', to='assets.inmueble', verbose_name='Inmueble')),
                ('tipo_garantia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrendamientos', to='core.tipogarantiaarrendamiento', verbose_name='Tipo de Garantía')),
            ],
            options={
                'verbose_name': 'Arrendamiento',
                'verbose_name_plural': 'Arrendamientos',
                'db_table': 'arrendamientos',
            },
        ),
        migrations.CreateModel(
            name='CompraventaInmueble',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Marca de tiempo automática al momento de la inserción.', verbose_name='Fecha de creación')),
                ('instrumento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='compraventa', serialize=False, to='instruments.instrumento', verbose_name='Instrumento Base')),
                ('precio_sin_iva', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Precio de Venta (sin IVA)')),
                ('deposito_garantia', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Depósito en Garantía')),
                ('es_promesa_contrato', models.BooleanField(default=False, help_text='True = Promesa de compraventa (pre-contrato). False = Contrato definitivo de compraventa.', verbose_name='¿Es Promesa de Contrato?')),
                ('plazo_pago_dias', models.IntegerField(blank=True, null=True, verbose_name='Plazo de Pago (días)')),
                ('fecha_firma_contrato_previo', models.DateField(blank=True, help_text='Si es promesa, fecha en que se firmó. Importante para calcular plazos de formalización.', null=True, verbose_name='Fecha de Firma de la Promesa')),
                ('creado_por', models.ForeignKey(blank=True, help_text='Usuario del sistema que registró este objeto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='compraventas', to='assets.inmueble', verbose_name='Inmueble')),
            ],
            options={
                'verbose_name': 'Compraventa de Inmueble',
                'verbose_name_plural': 'Compraventas de Inmuebles',
                'db_table': 'compraventas_inmuebles',
            },
        ),
        migrations.CreateModel(
            name='ServicioPrestado',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Marca de tiempo automática al momento de la inserción.', verbose_name='Fecha de creación')),
                ('instrumento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='servicio_prestado', serialize=False, to='instruments.instrumento', verbose_name='Instrumento Base')),
                ('honorarios_monto', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto de Honorarios')),
                ('frecuencia_pago', models.CharField(blank=True, help_text='Ej: Mensual, Quincenal, Por Entregable.', max_length=50, null=True, verbose_name='Frecuencia de Pago')),
                ('contraprestacion_total_monto', models.DecimalField(blank=True, decimal_places=2, help_text='Monto máximo presupuestado para la vigencia total del contrato.', max_digits=15, null=True, verbose_name='Contraprestación Total (Techo)')),
                ('tipo_entregable', models.CharField(blank=True, help_text='Ej: "Reporte Mensual", "Consultoría Estratégica", "Auditoría".', max_length=100, null=True, verbose_name='Tipo de Entregable')),
                ('fecha_entregable', models.DateField(blank=True, null=True, verbose_name='Fecha de Entregable')),
                ('requiere_repse', models.BooleanField(default=False, help_text='Si True, el contratista debe estar registrado en el REPSE conforme a la reforma LSS 2021.', verbose_name='¿Requiere REPSE?')),
                ('numero_registro_repse', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Registro REPSE')),
                ('creado_por', models.ForeignKey(blank=True, help_text='Usuario del sistema que registró este objeto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Servicio Prestado',
                'verbose_name_plural': 'Servicios Prestados',
                'db_table': 'servicios_prestados',
            },
        ),
        migrations.CreateModel(
            name='SuministroMercancia',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Marca de tiempo automática al momento de la inserción.', verbose_name='Fecha de creación')),
                ('instrumento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='suministro', serialize=False, to='instruments.instrumento', verbose_name='Instrumento Base')),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Subtotal Fijo')),
                ('monto_iva', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='IVA Fijo')),
                ('monto_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Total Fijo')),
                ('maximo_subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Máximo Subtotal')),
                ('maximo_iva', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Máximo IVA')),
                ('maximo_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Máximo Total (Techo)')),
                ('minimo_subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Mínimo Subtotal')),
                ('minimo_iva', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Mínimo IVA')),
                ('minimo_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Mínimo Total (Piso)')),
                ('anticipo_monto', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Anticipo')),
                ('fecha_entrega', models.DateField(blank=True, null=True, verbose_name='Fecha de Entrega Pactada')),
                ('creado_por', models.ForeignKey(blank=True, help_text='Usuario del sistema que registró este objeto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('domicilio_entrega', models.ForeignKey(help_text='Dirección a la que deben entregarse los bienes objeto del contrato.', on_delete=django.db.models.deletion.RESTRICT, related_name='suministros', to='addresses.domicilio', verbose_name='Domicilio de Entrega')),
            ],
            options={
                'verbose_name': 'Suministro de Mercancía',
                'verbose_name_plural': 'Suministros de Mercancías',
                'db_table': 'suministros_mercancias',
            },
        ),
        migrations.AddConstraint(
            model_name='instrumento',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_termino__isnull', True), ('fecha_termino__gte', models.F('fecha_inicio')), _connector='OR'), name='chk_fechas_instrumento'),
        ),
        migrations.AlterUniqueTogether(
            name='instrumentoparte',
            unique_together={('instrumento', 'parte', 'rol')},
        ),
        migrations.AddConstraint(
            model_name='suministromercancia',
            constraint=models.CheckConstraint(condition=models.Q(('maximo_total__isnull', True), ('minimo_total__isnull', True), ('maximo_total__gte', models.F('minimo_total')), _connector='OR'), name='chk_presupuesto_min_max'),
        ),
    ]
