# Generated by Django 6.0.3 on 2026-03-14 09:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Marca de tiempo automática al momento de la inserción.', verbose_name='Fecha de creación')),
                ('nombre_documento', models.CharField(max_length=512, verbose_name='Nombre del Documento')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('nombre_archivo', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Nombre del Archivo')),
                ('ruta_archivo', models.FileField(blank=True, help_text='PDF o documento del anexo. Almacenado cifrado en AWS S3 con AES256.', null=True, upload_to='documentos/anexos/', verbose_name='Archivo Digital (S3)')),
            ],
            options={
                'verbose_name': 'Anexo',
                'verbose_name_plural': 'Anexos',
                'db_table': 'anexos',
                'ordering': ['instrumento', 'nombre_documento'],
            },
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Marca de tiempo automática al momento de la inserción.', verbose_name='Fecha de creación')),
                ('nombre_archivo', models.CharField(max_length=1024, verbose_name='Nombre del Archivo')),
                ('ruta_archivo', models.FileField(help_text='Archivo de evidencia. Almacenado cifrado en AWS S3 con AES256.', upload_to='documentos/evidencias/', verbose_name='Evidencia Digital (S3)')),
                ('comentario', models.TextField(help_text='Contexto o descripción del contenido de la evidencia.', verbose_name='Comentario')),
            ],
            options={
                'verbose_name': 'Evidencia',
                'verbose_name_plural': 'Evidencias',
                'db_table': 'evidencias',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Modificatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Marca de tiempo automática al momento de la inserción.', verbose_name='Fecha de creación')),
                ('numero_modificatorio', models.IntegerField(help_text='Secuencial por contrato. Ej: 1 para "Convenio No. 1".', verbose_name='Número de Modificatorio')),
                ('titulo', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción / Resumen Ejecutivo')),
                ('fecha_emision', models.DateField(help_text='Fecha de firma o entrada en vigor del modificatorio.', verbose_name='Fecha de Emisión')),
                ('nombre_archivo', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Nombre del Archivo')),
                ('ruta_archivo', models.FileField(blank=True, null=True, upload_to='documentos/modificatorios/', verbose_name='Modificatorio Digital (S3)')),
            ],
            options={
                'verbose_name': 'Modificatorio',
                'verbose_name_plural': 'Modificatorios',
                'db_table': 'modificatorios',
                'ordering': ['instrumento', 'numero_modificatorio'],
            },
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Marca de tiempo automática al momento de la inserción.', verbose_name='Fecha de creación')),
                ('nombre_partida', models.CharField(help_text='Ej: "Laptop Dell Latitude", "Hora de Consultoría".', max_length=255, verbose_name='Nombre de la Partida')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Especificaciones Técnicas')),
                ('unidad_medida', models.CharField(help_text='Ej: Piezas, Horas, Licencias, Metros.', max_length=50, verbose_name='Unidad de Medida')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Unitario')),
                ('tasa_iva', models.DecimalField(decimal_places=2, default='0.16', help_text='Expresado como decimal. Ej: 0.16 para 16%, 0.00 para exento.', max_digits=5, verbose_name='Tasa de IVA')),
            ],
            options={
                'verbose_name': 'Partida',
                'verbose_name_plural': 'Partidas',
                'db_table': 'partidas',
                'ordering': ['anexo', 'nombre_partida'],
            },
        ),
        migrations.CreateModel(
            name='Addendum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Marca de tiempo automática al momento de la inserción.', verbose_name='Fecha de creación')),
                ('numero_addendum', models.IntegerField(verbose_name='Número de Addendum')),
                ('titulo', models.CharField(max_length=1024, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha_emision', models.DateField(verbose_name='Fecha de Emisión')),
                ('nombre_archivo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del Archivo')),
                ('ruta_archivo', models.FileField(blank=True, null=True, upload_to='documentos/addenda/', verbose_name='Addendum Digital (S3)')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('creado_por', models.ForeignKey(blank=True, help_text='Usuario del sistema que registró este objeto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Addendum',
                'verbose_name_plural': 'Addenda',
                'db_table': 'addenda',
                'ordering': ['instrumento', 'numero_addendum'],
            },
        ),
    ]
