# Generated by Django 6.0.3 on 2026-03-14 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('documents', '0001_initial'),
        ('instruments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='addendum',
            name='instrumento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addenda', to='instruments.instrumento', verbose_name='Instrumento'),
        ),
        migrations.AddField(
            model_name='addendum',
            name='tipo_addendum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addenda', to='core.tipoaddendum', verbose_name='Tipo de Addendum'),
        ),
        migrations.AddField(
            model_name='anexo',
            name='categoria_anexo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anexos', to='core.categoriaanexo', verbose_name='Categoría del Anexo'),
        ),
        migrations.AddField(
            model_name='anexo',
            name='creado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario del sistema que registró este objeto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
    ]
