# Generated by Django 6.0.3 on 2026-03-18 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('documents', '0002_initial'),
        ('instruments', '0002_initial'),
        ('legal', '0002_initial'),
        ('parties', '0001_initial'),
        ('tracking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='anexo',
            name='entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anexos', to='tracking.entrega', verbose_name='Entrega Asociada'),
        ),
        migrations.AddField(
            model_name='anexo',
            name='instrumento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='instruments.instrumento', verbose_name='Instrumento'),
        ),
        migrations.AddField(
            model_name='document',
            name='creado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario del sistema que registró este objeto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(help_text='Usuario que realizó la carga física del documento al sistema.', on_delete=django.db.models.deletion.PROTECT, related_name='documentos_cargados', to=settings.AUTH_USER_MODEL, verbose_name='Cargado por'),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='archivo_fisico_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias', to='instruments.archivofisico', verbose_name='Archivo Físico de Origen'),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='creado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario del sistema que registró este objeto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='escritura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias', to='legal.escritura', verbose_name='Escritura Relacionada'),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='instrumento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='instruments.instrumento', verbose_name='Instrumento'),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='parte',
            field=models.ForeignKey(blank=True, help_text='Parte que generó o remitió esta evidencia.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias', to='parties.parte', verbose_name='Parte Emisora'),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='tipo_copia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='evidencias', to='core.tipocopia', verbose_name='Tipo de Copia / Validez Legal'),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='tipo_evidencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='evidencias', to='core.tipoevidencia', verbose_name='Tipo de Evidencia'),
        ),
        migrations.AddField(
            model_name='modificatorio',
            name='creado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario del sistema que registró este objeto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='modificatorio',
            name='instrumento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modificatorios', to='instruments.instrumento', verbose_name='Instrumento'),
        ),
        migrations.AddField(
            model_name='modificatorio',
            name='tipo_modificatorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modificatorios', to='core.tipomodificatorio', verbose_name='Tipo de Modificatorio'),
        ),
        migrations.AddField(
            model_name='partida',
            name='anexo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='documents.anexo', verbose_name='Anexo'),
        ),
        migrations.AddField(
            model_name='partida',
            name='creado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario del sistema que registró este objeto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterUniqueTogether(
            name='addendum',
            unique_together={('instrumento', 'numero_addendum')},
        ),
        migrations.AlterUniqueTogether(
            name='anexo',
            unique_together={('instrumento', 'nombre_documento')},
        ),
        migrations.AlterUniqueTogether(
            name='modificatorio',
            unique_together={('instrumento', 'numero_modificatorio')},
        ),
        migrations.AlterUniqueTogether(
            name='partida',
            unique_together={('anexo', 'nombre_partida')},
        ),
    ]
