# Generated by Django 6.0.3 on 2026-03-14 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(help_text='Identificador primario del registro afectado.', max_length=50, verbose_name='ID del objeto')),
                ('atributo_modificado', models.JSONField(blank=True, help_text='Snapshot JSON con el estado "antes" y "después" del cambio.', null=True, verbose_name='Atributo modificado')),
                ('tipo_accion', models.CharField(help_text='Código de la operación realizada: CREACION, EDICION, VALIDACION, etc.', max_length=20, verbose_name='Tipo de acción')),
                ('comentario', models.TextField(blank=True, help_text='Justificación o descripción textual del cambio aplicado.', null=True, verbose_name='Comentario')),
                ('fecha_evento', models.DateTimeField(auto_now_add=True, help_text='Marca de tiempo inmutable del momento exacto de la acción.', verbose_name='Fecha del evento')),
                ('content_type', models.ForeignKey(help_text='Referencia al modelo afectado (ej: instrumentos, partes).', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de contenido')),
                ('usuario_autorizador', models.ForeignKey(blank=True, help_text='Usuario que aprobó o validó la acción (Checker).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_autorizados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Checker')),
                ('usuario_pre_registro', models.ForeignKey(blank=True, help_text='Usuario que propuso o ejecutó la acción (Maker).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_propuestos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Maker')),
            ],
            options={
                'verbose_name': 'Historial de Registro',
                'verbose_name_plural': 'Historial de Registros',
                'db_table': 'historial_registros',
                'ordering': ['-fecha_evento'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='historial_r_content_72c94a_idx')],
            },
        ),
    ]
