# Generated by Django 6.0.3 on 2026-03-14 09:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Marca de tiempo automática al momento de la inserción.', verbose_name='Fecha de creación')),
                ('unidad_medida_penalizada', models.CharField(blank=True, max_length=50, null=True, verbose_name='Unidad de Medida Penalizada')),
                ('cantidad_unidad_medida', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cantidad de Unidad')),
                ('dias_atraso', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Días de Atraso')),
                ('periodo_pena', models.CharField(blank=True, help_text='Ej: Diario, Semanal, Único.', max_length=100, null=True, verbose_name='Período de Pena')),
                ('monto_a_penalizar', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Base a Penalizar')),
                ('valor_pena_porcentaje', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje de Pena (%)')),
                ('monto_penalizado', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Monto Penalizado (resultado)')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentario')),
                ('link_factura', models.CharField(blank=True, max_length=512, null=True, verbose_name='Link / Nota de Crédito')),
            ],
            options={
                'verbose_name': 'Pena Convencional',
                'verbose_name_plural': 'Penas Convencionales',
                'db_table': 'penas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Fianza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Marca de tiempo automática al momento de la inserción.', verbose_name='Fecha de creación')),
                ('numero_poliza', models.CharField(max_length=100, verbose_name='Número de Póliza')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Monto Afianzado')),
                ('descripcion_obligacion', models.TextField(blank=True, null=True, verbose_name='Descripción de la Obligación')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Inicio de Vigencia')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fin de Vigencia')),
                ('nombre_archivo', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Nombre de Archivo')),
                ('ruta_archivo', models.FileField(blank=True, help_text='PDF del documento de la póliza. Se almacena cifrado en AWS S3 con AES256.', null=True, upload_to='garantias/fianzas/', verbose_name='Póliza Digital (S3)')),
                ('afianzadora', models.ForeignKey(blank=True, help_text='Empresa afianzadora o aseguradora que emitió la póliza.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fianzas_emitidas', to='parties.parte', verbose_name='Afianzadora (Fiador)')),
                ('creado_por', models.ForeignKey(blank=True, help_text='Usuario del sistema que registró este objeto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Fianza',
                'verbose_name_plural': 'Fianzas',
                'db_table': 'fianzas',
                'ordering': ['fecha_fin'],
            },
        ),
    ]
