# Generated by Django 6.0.3 on 2026-03-18 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('documents', '0002_initial'),
        ('guarantees', '0001_initial'),
        ('instruments', '0001_initial'),
        ('parties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fianza',
            name='afianzadora',
            field=models.ForeignKey(blank=True, help_text='Empresa afianzadora o aseguradora que emitió la póliza.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fianzas_emitidas', to='parties.parte', verbose_name='Afianzadora (Fiador)'),
        ),
        migrations.AddField(
            model_name='fianza',
            name='creado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario del sistema que registró este objeto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='fianza',
            name='instrumento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fianzas', to='instruments.instrumento', verbose_name='Instrumento'),
        ),
        migrations.AddField(
            model_name='fianza',
            name='tipo_fianza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='fianzas', to='core.tipofianza', verbose_name='Tipo de Fianza'),
        ),
        migrations.AddField(
            model_name='fianza',
            name='tipo_obligacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fianzas', to='core.tipoobligacion', verbose_name='Tipo de Obligación'),
        ),
        migrations.AddField(
            model_name='pena',
            name='addendum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penas', to='documents.addendum', verbose_name='Addendum de Origen'),
        ),
        migrations.AddField(
            model_name='pena',
            name='anexo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penas', to='documents.anexo', verbose_name='Anexo de Origen'),
        ),
        migrations.AddField(
            model_name='pena',
            name='creado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario del sistema que registró este objeto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='pena',
            name='instrumento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penas', to='instruments.instrumento', verbose_name='Instrumento'),
        ),
        migrations.AddField(
            model_name='pena',
            name='modificatorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penas', to='documents.modificatorio', verbose_name='Modificatorio de Origen'),
        ),
        migrations.AddField(
            model_name='pena',
            name='partida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penas', to='documents.partida', verbose_name='Partida Penalizada'),
        ),
        migrations.AddField(
            model_name='pena',
            name='tipo_dia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penas', to='core.tipodia', verbose_name='Tipo de Día'),
        ),
        migrations.AddField(
            model_name='fianza',
            name='pena',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fianzas', to='guarantees.pena', verbose_name='Pena Garantizada'),
        ),
    ]
