# Generated by Django 6.0.3 on 2026-03-14 09:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('instruments', '0001_initial'),
        ('parties', '0002_personafisica_alter_parte_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Marca de tiempo automática al momento de la inserción.', verbose_name='Fecha de creación')),
                ('numero_entrega', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número de Entrega')),
                ('total_entregas_esperadas', models.IntegerField(blank=True, null=True, verbose_name='Total de Entregas Esperadas')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha_programada', models.DateField(verbose_name='Fecha Programada (Contractual)')),
                ('fecha_real', models.DateField(blank=True, null=True, verbose_name='Fecha Real de Recepción')),
                ('creado_por', models.ForeignKey(blank=True, help_text='Usuario del sistema que registró este objeto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('estatus_entrega', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='entregas', to='core.estatusentrega', verbose_name='Estatus')),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='instruments.instrumento', verbose_name='Instrumento')),
                ('tipo_entrega', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='entregas', to='core.tipoentrega', verbose_name='Tipo de Entrega')),
            ],
            options={
                'verbose_name': 'Entrega',
                'verbose_name_plural': 'Entregas',
                'db_table': 'entregas',
                'ordering': ['instrumento', 'numero_entrega'],
            },
        ),
        migrations.CreateModel(
            name='Hito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Marca de tiempo automática al momento de la inserción.', verbose_name='Fecha de creación')),
                ('titulo', models.CharField(max_length=1024, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha_meta', models.DateField(help_text='Fecha contractual en que debe cumplirse el hito.', verbose_name='Fecha Límite (Deadline)')),
                ('fecha_cumplimiento', models.DateField(blank=True, null=True, verbose_name='Fecha Real de Cumplimiento')),
                ('justificacion_atraso', models.TextField(blank=True, null=True, verbose_name='Justificación del Atraso')),
                ('creado_por', models.ForeignKey(blank=True, help_text='Usuario del sistema que registró este objeto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('estatus_hito', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='hitos', to='core.estatushito', verbose_name='Estatus')),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hitos', to='instruments.instrumento', verbose_name='Instrumento')),
                ('prioridad_hito', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='hitos', to='core.prioridadhito', verbose_name='Prioridad')),
                ('tipo_hito', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='hitos', to='core.tipohito', verbose_name='Tipo de Hito')),
            ],
            options={
                'verbose_name': 'Hito',
                'verbose_name_plural': 'Hitos',
                'db_table': 'hitos',
                'ordering': ['fecha_meta'],
            },
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Marca de tiempo automática al momento de la inserción.', verbose_name='Fecha de creación')),
                ('titulo', models.CharField(max_length=1024, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('creado_por', models.ForeignKey(blank=True, help_text='Usuario del sistema que registró este objeto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('estatus_actividad', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='actividades', to='core.estatusactividad', verbose_name='Estatus')),
                ('prioridad_actividad', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='actividades', to='core.prioridadactividad', verbose_name='Prioridad')),
                ('responsable', models.ForeignKey(help_text='Parte (persona u organización) obligada a ejecutar esta actividad.', on_delete=django.db.models.deletion.RESTRICT, related_name='actividades_asignadas', to='parties.parte', verbose_name='Responsable')),
                ('tipo_actividad', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='actividades', to='core.tipoactividad', verbose_name='Tipo de Actividad')),
                ('hito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='tracking.hito', verbose_name='Hito')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'db_table': 'actividades',
                'ordering': ['fecha_fin', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Marca de tiempo automática al momento de la inserción.', verbose_name='Fecha de creación')),
                ('titulo', models.CharField(max_length=1024, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('nombre_archivo', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Nombre de Archivo')),
                ('ruta_archivo', models.FileField(blank=True, null=True, upload_to='seguimiento/incidencias/', verbose_name='Evidencia de Incidencia (S3)')),
                ('monto_impacto', models.DecimalField(decimal_places=2, default=0, help_text='Costo o riesgo económico de la incidencia.', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto de Impacto')),
                ('monto_beneficio', models.DecimalField(decimal_places=2, default=0, help_text='Valor económico generado al resolver la incidencia.', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto de Beneficio')),
                ('fecha_ocurrencia', models.DateField(verbose_name='Fecha de Ocurrencia')),
                ('fecha_solucion', models.DateField(blank=True, null=True, verbose_name='Fecha de Solución')),
                ('actividad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias', to='tracking.actividad', verbose_name='Actividad Relacionada')),
                ('creado_por', models.ForeignKey(blank=True, help_text='Usuario del sistema que registró este objeto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('estatus_incidencia', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='incidencias', to='core.estatusincidencia', verbose_name='Estatus')),
                ('gravedad_incidencia', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='incidencias', to='core.gravedadincidencia', verbose_name='Gravedad')),
                ('tipo_incidencia', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='incidencias', to='core.tipoincidencia', verbose_name='Tipo de Incidencia')),
            ],
            options={
                'verbose_name': 'Incidencia',
                'verbose_name_plural': 'Incidencias',
                'db_table': 'incidencias',
                'ordering': ['-fecha_ocurrencia'],
            },
        ),
        migrations.AddConstraint(
            model_name='actividad',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_fin__isnull', True), ('fecha_inicio__isnull', True), ('fecha_fin__gte', models.F('fecha_inicio')), _connector='OR'), name='chk_fechas_actividad'),
        ),
    ]
